### ISSUE TITLE
Add ability to setup password via environment variable and ask on startup

### ISSUE THREAD

**Issue by wchan-ranelagh** [linuxserver/docker-firefox#2]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

It would be good to be able to override the default password of abc/abc as an environment variable, and another environment variable to configure whether on startup when the user connects to this via their browser, it will ask them for a password first or not.  In our use case, we want to generate a random password, set it the docker instance via the env variable, and then the user has to use that generated random password to authenticate before they can use it (so forcing them through the flow as if they used the ?login=true query parameter)

## Current Behavior

Currently it defaults to the abc/abc username/password and unless the user use ?login=true query parameter it doesn't force them to login.

## Alternatives Considered

We thought about potentially a docker mod but thought this functionality would be useful for others anyway and much simpler to setup as just environment variables.

**Comment by tobbenb** [comment]
In the Calibre container, that uses the same baseimage, you can set the PASSWORD env variable to change the password for ABC, so I assume this is the same in this container. 
I then think it will force the user to log in.

**Comment by wchan-ranelagh** [comment]
> In the Calibre container, that uses the same baseimage, you can set the PASSWORD env variable to change the password for ABC, so I assume this is the same in this container.
> I then think it will force the user to log in.

Doesn't look like it.  I tried that env variable and it didn't do anything to the password and it is still "abc"

**Comment by aptalca** [comment]
abc:abc are the default credentials and as long they are set, guac client uses autologin (no prompt). But if you change the password to anything else, autologin will fail and it will prompt for password. It's all PAM based. I guess we didn't add the info on how to change the password, but you can run `docker exec -it firefox passwd abc` and it will prompt you for a new password. After which point, you'll be prompted for that password every time you try to connect.

In calibre, we baked in env var functionality because it had that prior to being rebased on the new rdesktop-web baseimage.

**Comment by wchan-ranelagh** [comment]
> abc:abc are the default credentials and as long they are set, guac client uses autologin (no prompt). But if you change the password to anything else, autologin will fail and it will prompt for password. It's all PAM based. I guess we didn't add the info on how to change the password, but you can run `docker exec -it firefox passwd abc` and it will prompt you for a new password. After which point, you'll be prompted for that password every time you try to connect.
> 
> In calibre, we baked in env var functionality because it had that prior to being rebased on the new rdesktop-web baseimage.

Hi,

So is it possible to bring that "feature" back of setting the password via environment variable?  We are trying to set it when we create the instance rather than manually after the instance comes up via the exec command.

Thanks!

**Comment by aptalca** [comment]
There is no "bringing back" as it never existed in this baseimage or final image. It was only added to calibre for backwards compatibility.

Someone can PR, I guess. It's just not a high enough priority for me at the moment.
