### ISSUE TITLE
[BUG] Firefox not showing up on Kasm Web UI

### ISSUE THREAD

**Issue by monethass** [linuxserver/docker-firefox#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After starting the container, `docker exec firefox ps aux` shows Firefox is running, but the Kasm Web UI only shows the "desktop" and not Firefox. Before Kasm, Firefox launches and shows up without problem.

Screenshot of web UI: https://ibb.co/Yd23MSh

`docker exec firefox ps aux`:
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0    200    64 ?        Ss   10:57   0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
root          15  0.0  0.0    204    68 ?        S    10:57   0:00 s6-supervise s6-linux-init-shutdownd
root          16  0.0  0.0    192     4 ?        Ss   10:57   0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
root          68  0.0  0.0    204    64 ?        S    10:57   0:00 s6-supervise svc-docker
root          69  0.0  0.0    204    64 ?        S    10:57   0:00 s6-supervise s6rc-fdholder
root          70  0.0  0.0    204    68 ?        S    10:57   0:00 s6-supervise s6rc-oneshot-runner
root          71  0.0  0.0    204    68 ?        S    10:57   0:00 s6-supervise svc-kasmvnc
root          72  0.0  0.0    204    68 ?        S    10:57   0:00 s6-supervise svc-pulseaudio
root          73  0.0  0.0    204    68 ?        S    10:57   0:00 s6-supervise svc-kclient
root          74  0.0  0.0    204    64 ?        S    10:57   0:00 s6-supervise svc-nginx
root          75  0.0  0.0    204    64 ?        S    10:57   0:00 s6-supervise svc-de
root          83  0.0  0.0    180     4 ?        Ss   10:57   0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --
abc          210  0.0  0.0 341180  6680 ?        Ssl  10:57   0:00 /usr/bin/pulseaudio --log-level=0 --log-target=stderr --exit-idle-time=-1
abc          213  0.0  0.0  10968  5024 ?        Sl   10:57   0:00 /usr/libexec/pulse/gsettings-helper
abc          216  1.5  0.3 190400 74532 ?        Ssl  10:57   0:00 /usr/local/bin/Xvnc :1 -drinode /dev/dri/renderD128 -disableBasicAuth -SecurityTypes None -AlwaysShared -http-header Cross-Origin-Embedder-Policy=require-corp -http-header Cross-Origin-Opener-Policy=same-origin -geometry 1024x768 -sslOnly 0 -RectThreads 0 -websocketPort 6901 -interface 0.0.0.0 -Log *:stdout:10
abc          222  1.5  0.2 550416 55040 ?        Ssl  10:57   0:00 node index.js
root         227  0.0  0.0   9652  5836 ?        Ss   10:57   0:00 nginx: master process /usr/sbin/nginx -g daemon off;
abc          234  0.0  0.0   2608  1720 ?        Ss   10:57   0:00 /bin/bash /defaults/startwm.sh
abc          241  0.5  0.0  35876 21588 ?        S    10:57   0:00 /usr/bin/openbox --startup /usr/libexec/openbox-autostart OPENBOX
root         242  0.0  0.0   2616  1660 ?        Ss   10:57   0:00 bash ./run
nginx        258  0.0  0.0  10100  2960 ?        S    10:57   0:00 nginx: worker process
nginx        259  0.0  0.0  10168  2992 ?        S    10:57   0:00 nginx: worker process
nginx        260  0.0  0.0  10100  2960 ?        S    10:57   0:00 nginx: worker process
nginx        261  0.0  0.0  10100  2960 ?        S    10:57   0:00 nginx: worker process
abc          278  0.0  0.0   3476   184 ?        S    10:57   0:00 dbus-launch --autolaunch 19dcc2770a7aafff4114ea926432092e --binary-syntax --close-stderr
abc          279  0.0  0.0   1624  1052 ?        Ss   10:57   0:00 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
abc          294  0.0  0.0   1692  1108 ?        S    10:57   0:00 /bin/sh /usr/libexec/openbox-autostart OPENBOX
abc          299  0.0  0.0   1692     4 ?        S    10:57   0:00 sh /config/.config/openbox/autostart
abc          300 34.0  1.6 11243808 402104 ?     Sl   10:57   0:10 /usr/lib/firefox/firefox
abc          365  0.1  0.2 182492 59848 ?        Sl   10:57   0:00 /usr/lib/firefox/firefox -contentproc -parentBuildID 20230130132623 -prefsLen 19623 -prefMapSize 225984 -appDir /usr/lib/firefox/browser {34f341e2-6370-48bb-b345-3849cd4c6035} 300 socket
abc          383  1.2  0.4 2378384 106324 ?      Sl   10:57   0:00 /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 20020 -prefMapSize 225984 -jsInitLen 247032 -parentBuildID 20230130132623 -appDir /usr/lib/firefox/browser {b45c8383-0395-442e-869f-53eb15b8ca01} 300 tab
abc          402  1.8  0.5 2388516 124520 ?      Sl   10:57   0:00 /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 21146 -prefMapSize 225984 -jsInitLen 247032 -parentBuildID 20230130132623 -appDir /usr/lib/firefox/browser {f747ec1b-b93f-4905-aa54-b069d1c8332b} 300 tab
abc          496  0.3  0.3 2354308 83800 ?       Sl   10:57   0:00 /usr/lib/firefox/firefox -contentproc -childID 3 -isForBrowser -prefsLen 28470 -prefMapSize 225984 -jsInitLen 247032 -parentBuildID 20230130132623 -appDir /usr/lib/firefox/browser {58d332ba-ee8b-4e9f-bb2e-471dcaa7149b} 300 tab
abc          498  0.2  0.3 2354324 82804 ?       Sl   10:57   0:00 /usr/lib/firefox/firefox -contentproc -childID 4 -isForBrowser -prefsLen 28470 -prefMapSize 225984 -jsInitLen 247032 -parentBuildID 20230130132623 -appDir /usr/lib/firefox/browser {3d45ba87-8ba7-4727-8ada-62a93d9607ad} 300 tab
abc          525  0.3  0.3 2354324 82312 ?       Sl   10:57   0:00 /usr/lib/firefox/firefox -contentproc -childID 5 -isForBrowser -prefsLen 28662 -prefMapSize 225984 -jsInitLen 247032 -parentBuildID 20230130132623 -appDir /usr/lib/firefox/browser {986aab43-5bb7-47a3-ae29-f9dcbeb6e14e} 300 tab
root         541  0.0  0.0   2736   916 ?        S    10:57   0:00 sleep infinity
root         610  0.0  0.0   1868   932 ?        Rs   10:58   0:00 ps aux
```

### Expected Behavior

Firefox showing up in web UI.

### Steps To Reproduce

1. arm64, Ubuntu Server 22.04 host
2. Start container
3. Open web UI

### Environment

```markdown
- OS: Ubuntu Server 22.04
- How docker service was installed: with script from Docker's website
```

### CPU architecture

arm64

### Docker creation

```bash
`docker-compose.yml`:

version: "3"
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:firefox-fonts
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "4gb"
    restart: unless-stopped

```
```


### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:firefox-fonts files to container
[mod-init] linuxserver/mods:firefox-fonts applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

**** Adding firefox-fonts packages to install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
(1/5) Installing font-croscore (0_git20211101-r6)
(2/5) Installing font-noto-emoji (2.038-r0)
(3/5) Installing encodings (1.0.6-r0)
(4/5) Installing mkfontscale (1.2.2-r1)
(5/5) Installing font-dejavu (2.37-r3)
Executing busybox-1.35.0-r29.trigger
Executing fontconfig-2.14.1-r0.trigger
Executing mkfontscale-1.2.2-r1.trigger
OK: 949 MiB in 265 packages
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.1.0 - built Apr  9 2023 00:38:48
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D (t=1.6893) [GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D
```
```

**Comment by Atomspion** [comment]
Probably same error here, Unraid on x86:

Logmessage:
Obt-Message: Xinerama extension is not present on the server
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D (t=1.20744) [GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D

**Comment by IC3P3** [comment]
I've got the same error I think
`[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D (t=0.619822) [GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D`

**Comment by lczerner** [comment]
Interestingly enough the https://github.com/linuxserver/docker-baseimage-kasmvnc behaves the same way no matter what GUI application I try to run, not just firefox. Nothing shows up in the VNC viewer, no errors as far as I can see.

My understanding is also that there is supposed to be a way of launching the GUI application directly from the desktop as there should be some kind of menu present. Nothing resembling this shows up either.

**Comment by thelamer** [comment]
@lczerner host info please and docker setup. 
`uname -a`
`runc --version`
`docker --version`

**Comment by sorryusernameisalreadytaken** [comment]
I have the same issue.
Host: [omv ](https://www.openmediavault.org/)
uname -a:
´´´Linux omv 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux´´´
runc --version:
´´´
runc version 1.1.5
commit: v1.1.5-0-gf19387a
spec: 1.0.2-dev
go: go1.19.7
libseccomp: 2.5.1
´´´
docker --version:
´´´Docker version 23.0.3, build 3e7cbfd´´´

**Comment by thelamer** [comment]
> I have the same issue. Host: [omv ](https://www.openmediavault.org/) uname -a: `Linux omv 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux` runc --version:
> 
> ```
> runc version 1.1.5
> commit: v1.1.5-0-gf19387a
> spec: 1.0.2-dev
> go: go1.19.7
> libseccomp: 2.5.1
> ```
> 
> docker --version: `Docker version 23.0.3, build 3e7cbfd`
> 
> Last working image: `lscr.io/linuxserver/firefox:101.0.1` Not working image: `lscr.io/linuxserver/firefox:109.0.1-r0-ls87`

Same issue as in Firefox tries to start up at 100% cpu for like 5-10 minutes then suddenly loads? 
Where you can manually kill two pids for the stuck Firefox and it will then load? 
If so it seems like this is a Firefox thing and Kernel 6 host level, all reports of this and my own testing were running kernel 6+. 

There is not really anything I can do to fix that, my only recommendation would be to use the chromium image https://github.com/linuxserver/docker-chromium

**Comment by sorryusernameisalreadytaken** [comment]
okay, I am confused. My docker-firefox latest is back again:
![image](https://user-images.githubusercontent.com/12913436/232029909-c0db5691-d7e0-4569-bd4f-9bbba99e33d8.png)
But I have no idea why. I did a lot of tests yesterday and today, the action was to run [docker-chromium](https://github.com/linuxserver/docker-chromium) on another port and due to an problem when running [docker-chromium](https://github.com/linuxserver/docker-chromium) and [docker-firefox](https://github.com/linuxserver/docker-firefox) on the same time (both using internal as default port 3000 and 3001) I simply down the testing compose for the [docker-chromium](https://github.com/linuxserver/docker-chromium) and restart my [docker-firefox](https://github.com/linuxserver/docker-firefox) testing compose.

Perhaps some hints:
-increased the given ram to 4gb instead of 1gb for a short time
-force-recreate the testing-docker-compose once
-changed the autorun file within the contaoner (exec into it)once to "firefox --ProfileManager"

**Comment by thelamer** [comment]
> okay, I am confused. My docker-firefox latest is back again: ![image](https://user-images.githubusercontent.com/12913436/232029909-c0db5691-d7e0-4569-bd4f-9bbba99e33d8.png) But I have no idea why. I did a lot of tests yesterday and today, the action was to run [docker-chromium](https://github.com/linuxserver/docker-chromium) on another port and due to an problem when running [docker-chromium](https://github.com/linuxserver/docker-chromium) and [docker-firefox](https://github.com/linuxserver/docker-firefox) on the same time (both using internal as default port 3000 and 3001) I simply down the testing compose for the [docker-chromium](https://github.com/linuxserver/docker-chromium) and restart my [docker-firefox](https://github.com/linuxserver/docker-firefox) testing compose.
> 
> Perhaps some hints: -increased the given ram to 4gb instead of 1gb for a short time -force-recreate the testing-docker-compose once -changed the autorun file within the contaoner (exec into it)once to "firefox --ProfileManager"

That's good info, the profile generation might be to blame I'll look at that angle.

**Comment by tracerrx** [comment]
changing shm_size: "1gb" to shm_size: "5gb" fixed it for me (on synology).

**Comment by tracerrx** [comment]
Working on synology DSM 7 Docker.

**Comment by thelamer** [comment]
Ok, thats good, I don't think the shm changes are needed the race condition was random and that was more likely it.

**Comment by sorryusernameisalreadytaken** [comment]
> I have the same issue. Host: [omv ](https://www.openmediavault.org/) uname -a: `Linux omv 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux` runc --version:
> 
> ```
> runc version 1.1.5
> commit: v1.1.5-0-gf19387a
> spec: 1.0.2-dev
> go: go1.19.7
> libseccomp: 2.5.1
> ```
> 
> docker --version: `Docker version 23.0.3, build 3e7cbfd`
> 
I can confirm that it is working again with my original 2gb shm size.

THX a lot @thelamer <3

**Comment by monethass** [comment]
I can also confirm it's working.

**Comment by oatsvine** [comment]
I have the same problem except it starts after "a while" (the better part of an hour). I see it using a full core during this warm up period.
```
❯ dc exec firefox ps aux --sort pcpu | tail -n1
abc          261 99.8  0.1 330748 16576 ?        R    17:19   5:44 /usr/lib/firefox/firefox
```
I haven't investigated the issue. I'll try increasing  `shm_size`.
