### ISSUE TITLE
[BUG] container won't start when using kasmvnc base

### ISSUE THREAD

**Issue by Extcee** [linuxserver/docker-firefox#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting the container, it fails with

`mv: cannot move '/usr/local/etc/kasmvnc/kasmvnc.yaml.lsio' to a subdirectory of itself, '/usr/local/etc/kasmvnc/kasmvnc.yaml'
27
s6-rc: warning: unable to start service init-kasmvnc-config: command exited 1`

This appears to happen on both Firefox and Webtop which have recently changed base to kasmvnc

### Expected Behavior

Container to start normally and load service

### Steps To Reproduce

1. Pull container with docker compose
2. Start container and view logs for error

### Environment

```markdown
- OS:Ubuntu 22.04
- How docker service was installed: using docker docs repo (not snap or pip package)
```

### CPU architecture

x86-64

### Docker creation

```bash
firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
2
[migrations] no migrations found
3
───────────────────────────────────────
4
5
      ██╗     ███████╗██╗ ██████╗ 
6
      ██║     ██╔════╝██║██╔═══██╗
7
      ██║     ███████╗██║██║   ██║
8
      ██║     ╚════██║██║██║   ██║
9
      ███████╗███████║██║╚██████╔╝
10
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
11
12
   Brought to you by linuxserver.io
13
───────────────────────────────────────
14
15
To support LSIO projects visit:
16
https://www.linuxserver.io/donate/
17
18
───────────────────────────────────────
19
GID/UID
20
───────────────────────────────────────
21
22
User UID:    1000
23
User GID:    1000
24
───────────────────────────────────────
25
26
mv: cannot move '/usr/local/etc/kasmvnc/kasmvnc.yaml.lsio' to a subdirectory of itself, '/usr/local/etc/kasmvnc/kasmvnc.yaml'
27
s6-rc: warning: unable to start service init-kasmvnc-config: command exited 1
```

**Comment by thelamer** [comment]
Someone just posted the exact same issue and they were not running Docker: 
https://github.com/linuxserver/docker-calibre/issues/130

Are you sure you have not applied any other hardening to this container? The error seems to indicate the underlying in container filesystem is read only.

**Comment by Extcee** [comment]
Thanks for the link, I didn't see that post - I also have my docker stack running in a proxmox lxc container.

**Comment by thelamer** [comment]
In any case it looks like given internal testing LXC needs to run in privileged mode for these containers to work with LXC.
