### ISSUE TITLE
[FEAT] Any instructions to add CJK fonts support?

### ISSUE THREAD

**Issue by samuelhbne** [linuxserver/docker-firefox#27]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Can we add Chinese/Japanese/Korean fonts support or provide the instructions for end user to add them? Thanks.

### Reason for change

To enable CJK page display

**Comment by thespad** [comment]
See https://github.com/linuxserver/docker-mods/tree/universal-internationalization
