### ISSUE TITLE
Allow to change the internal port (Or set another value)

### ISSUE THREAD

**Issue by MilesTEG1** [linuxserver/docker-firefox#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior & Current Behavior

I want to use the docker-firefox and docker-filezilla behind a docker-vpn.
I can have Firefox behind the VPN, or Filezilla behind the VPN, but not the two behind the VPN because both (firefox and filezilla) are using the same internal 3000 port, and with the VPN in front of them, I have to declare the port in the VPN service (in my docker-compose.yml), and two 3000 inside port aren't possible (or I don't know how to do it).

## Alternatives Considered

I could create 2 docker-compose : 

- One with VPN + Filezilla
- Another one with VPN + Firefox.

But by doing this, I can't have another VPN connexion elsewhere... ANd That's not a very good solution for me.

So, the best way is to set an inside port for Filezilla different from the one for Firefox, in hard coding, or, by letting the user change it with a ENV variable.
Is it possible ?
Thanks.

**Comment by thelamer** [comment]
`-e CUSTOM_PORT=3001`
