### ISSUE TITLE
[FEAT] persian support

### ISSUE THREAD

**Issue by amirhosseinds** [linuxserver/docker-firefox#30]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi there 
If its possible add support persian language show in browser currently it cant show the persian language
you can see the problem in attached file.
thanks.

![persian_problem](https://github.com/linuxserver/docker-firefox/assets/49087546/598c4789-f582-46d9-af02-db206cf720be)

### Reason for change

this is need browser can handle all languages

**Comment by thespad** [comment]
Take a look at https://github.com/linuxserver/docker-mods/tree/universal-internationalization and see if it meets your requirements.

**Comment by amirhosseinds** [comment]
problem solved
thanks very much
