### ISSUE TITLE
[FEAT] Ability to make container storage persistent

### ISSUE THREAD

**Issue by Jacksaur** [linuxserver/docker-firefox#35]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Apologies if this is already possible, but I couldn't seem to accomplish this by creating volumes. Firefox would create profile folders and settings, but wouldn't save them between restarts.

It would be helpful it it was possible to make Firefox's profile folder persistent, so that all settings remain between restarts of the container.

### Reason for change

Being able to keep all profile data between restarts would be extremely useful. Not only in being able to resume previous sessions with history intact, but also to keep installed addons and browser settings. It could provide use in having a separate, containerised version of firefox with specific addons for a specific use case, whilst avoiding bloat on the user's main browser.

**Comment by Jacksaur** [comment]
That's what I assumed, but with:
volumes:
    - ${ROOT}/firefox:/config

In my docker compose, it seems to write but not read the profile files it leaves behind.

**Comment by j0nnymoe** [comment]
And what do you have set as ${ROOT} ? I suspect you've got permissions issues.

**Comment by Jacksaur** [comment]
ROOT is /home/user/containers/media-stack/appdata/

My other containers are working fine with the path, but I'll check through the folders and see if anything is weird with their perms.

**Comment by Jacksaur** [comment]
After updating my container and appending :rw to the volume path, profile now seems to be saved as expected. No idea what's wrong with my filesystem that caused problems with this specific container, but I'm fine with this workaround.

Apologies for the unnecessary Issue.
