### ISSUE TITLE
[FEAT] Download Feature

### ISSUE THREAD

**Issue by kaaax0815** [linuxserver/docker-firefox#37]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Be able to download file from firefox to local browser.

If I currently download a file it downloads it to the containers filesystem and I have no way of downloading it.

### Reason for change

Good way to bypass certain Firewalls

**Comment by thelamer** [comment]
There is a file manager baked into the kclient application, click the sidebar and then click the file icon on the top. That is how you enable/disable audio as well.
