### ISSUE TITLE
[BUG] <setting cloudflares browser rendering to vnc breaks this and wont allow the connection>

### ISSUE THREAD

**Issue by osnapitsjoey** [linuxserver/docker-firefox#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

im trying to get a better refresh rate as im only getting 20fps on a coomputer not more than 5 miles from my server and I wanted to see if setting the cloudflare browser rendering to vnc would help. insead i get a broken page that says"The origin has unexpectedly closed the connection. Please confirm that the origin is healthy." and in the inspect window I see "WebSocket connection to 'wss://web.blank.com/' failed" 

again, this works if i do not set browser rending to anything, but i cannot get more than 20fps

### Expected Behavior

the page should load

### Steps To Reproduce

going to zero trust in cloudflare and changing "browser rending" from none to VNC

### Environment

```markdown
unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
unraid official linux server image
```

### Container logs

```bash
2023-11-16 15:20:56,251 [PRIO] Connections: accepted: @**.**.***.9**_**********.******::websocket
 2023-11-16 15:34:55,910 [PRIO] VNCSConnST: Failed to flush remaining socket data on close: write: Broken pipe (32)
 2023-11-16 15:34:55,910 [PRIO] Connections: closed: @**.**.***.9**_**********.******::websocket(write: Broken pipe (32))
```

**Comment by thelamer** [comment]
You are layering remote browser on a remote browser I am not entirely sure what you think I can do to fix this, I have never used RBI and you should likely take this up with them.

**Comment by osnapitsjoey** [comment]
> You are layering remote browser on a remote browser I am not entirely sure what you think I can do to fix this, I have never used RBI and you should likely take this up with them.

ooooh is that what im doing? i figured from the cloudflare documentation is was a streamlined way of passing vnc through there tunnel service
