### ISSUE TITLE
[BUG] failed to load driver: zink

### ISSUE THREAD

**Issue by TriCogz** [linuxserver/docker-firefox#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
.....+......+.....+....+...........+................+...+..+.+.....+....+.........+..+...+++++++++++++++++++++++++++++++++++++++*.+...+..+++++++++++++++++++++++++++++++++++++++*....+..........+...+......+.........+............+.....+.............+..+...+....+...............+............+........+.......+.....+.+..+.+.....+.+...........+...+......+......+....+..............+....+...++++++
.+..+.........+..........+.....+.+...+..+.+..............+.............+........+.......+..+.........+.......+...+..+...+++++++++++++++++++++++++++++++++++++++*....+......+......+.+..+++++++++++++++++++++++++++++++++++++++*..+..+.......+..+...+.+.........+........+.......+..+.+...............+...............+..+...+...+.+.........+..+.........+.+....................+.......+.....+......+.......+...+.....+......+.+...+...........+...+.....................+......+.+..+...+.......+.....+...+...+....+.................+...+......+.+...............+...........+......................+............+.....+...+.+..+....++++++
-----
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Xvnc KasmVNC 1.2.0 - built Feb  3 2024 18:41:28
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
[ls.io-init] done.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
Obt-Message: Xinerama extension is not present on the server
MESA: error: ZINK: vkEnumeratePhysicalDevices failed (VK_ERROR_INITIALIZATION_FAILED)
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink

### Steps To Reproduce

stack deploy and look at logs

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /path/to/config:/config
    ports:
      - 3080:3000
      - 81:3001
    shm_size: "1gb"
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
.....+......+.....+....+...........+................+...+..+.+.....+....+.........+..+...+++++++++++++++++++++++++++++++++++++++*.+...+..+++++++++++++++++++++++++++++++++++++++*....+..........+...+......+.........+............+.....+.............+..+...+....+...............+............+........+.......+.....+.+..+.+.....+.+...........+...+......+......+....+..............+....+...++++++
.+..+.........+..........+.....+.+...+..+.+..............+.............+........+.......+..+.........+.......+...+..+...+++++++++++++++++++++++++++++++++++++++*....+......+......+.+..+++++++++++++++++++++++++++++++++++++++*..+..+.......+..+...+.+.........+........+.......+..+.+...............+...............+..+...+...+.+.........+..+.........+.+....................+.......+.....+......+.......+...+.....+......+.+...+...........+...+.....................+......+.+..+...+.......+.....+...+...+....+.................+...+......+.+...............+...........+......................+............+.....+...+.+..+....++++++
-----
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Xvnc KasmVNC 1.2.0 - built Feb  3 2024 18:41:28
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
[ls.io-init] done.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
Obt-Message: Xinerama extension is not present on the server
MESA: error: ZINK: vkEnumeratePhysicalDevices failed (VK_ERROR_INITIALIZATION_FAILED)
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink
```

**Comment by thelamer** [comment]
Those errors are not fatal, what happens when you go to the web interface ?

**Comment by thelamer** [comment]
I assume it still works as everyone not mounting in a DRI3 compatible video card at /dev/dri would get this message.

**Comment by TriCogz** [comment]
![asfddsfafdsfds](https://github.com/linuxserver/docker-firefox/assets/145073837/0efc70df-9f1d-40b3-b65d-dc71e6782e43)
This is all I see.

**Comment by thelamer** [comment]
In your Docker config you set 81 to the https port (3001) but in your browser you are accessing it with http. 
Use https:// for port 81 and http:// for port 3080.

**Comment by TriCogz** [comment]
I swapped them added the https and it did work, but it worked on blocked ports. Interesting. Thank you.

**Comment by thelamer** [comment]
It was your browser cache, whenever you test a web app in the future use a private window.
