### ISSUE TITLE
Support for ARM v7

### ISSUE THREAD

**Issue by Pllet** [linuxserver/docker-firefox#43]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi, i am trying to use this on a raspberry pi 4b but it seems it does not support arm v7

![image](https://github.com/linuxserver/docker-firefox/assets/13187646/c3f40d7c-5da2-4239-87a1-4b56634755d7)

### Reason for change

to support raspberry

**Comment by j0nnymoe** [comment]
You need to update your rpi4 to 64bit.
https://info.linuxserver.io/issues/2023-07-01-armhf/

**Comment by Roxedus** [comment]
We do no longer support armhf/armv7. https://www.linuxserver.io/blog/a-farewell-to-arm-hf

You should reinstall your OS to 64bit, as your hardware is 64bit capable.

**Comment by Pllet** [comment]
oh i see, thanks, im kinda new with this and i thougth that my raspbian was 64bit... ill update, thanks a lot.
