### ISSUE TITLE
[BUG] Can't upload to filebrowser more than 2GB

### ISSUE THREAD

**Issue by luckyzor** [linuxserver/docker-firefox#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I'm using this container to upload files to a filebrowser instance, but I can't upload files bigger than 2GB.

### Expected Behavior

Be able to complete upload files no matter the size

### Steps To Reproduce

go to filebrowser website, upload file, choose file, hit upload
PS: on the firefox installed on my PC, I'm able to perform this.

config of the docker:

![image](https://github.com/linuxserver/docker-firefox/assets/31155573/2a22dc41-bcd7-4791-a6ff-1f500eceba8f)

### Environment

```markdown
- OS: Unraid
- How docker service was installed:
via APPS
```

### CPU architecture

x86-64

### Docker creation

```bash
created via Unraid
```

### Container logs

```bash
nothing on the logs
```

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-baseimage-kasmvnc/issues/59
