### ISSUE TITLE
[BUG] clipboard-read permission error being constantly thrown

### ISSUE THREAD

**Issue by Gylesie** [linuxserver/docker-firefox#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The issue is described and discussed here: https://github.com/kasmtech/KasmVNC/issues/219

It has been already resolved in KasmVNC 1.3.1. This image uses older version 1.3.0.

### Expected Behavior

No popup error

### Steps To Reproduce

1. Open a browser

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
.
```

**Comment by uniquegch** [comment]
clipboard-read (value of 'name' membe rof PermissionDescriptor) is not a valid value for enumartion PermissionName
I got this error message out of the blue on 1.14.0 and cannot click it away. I thought upgrading to 1.15.0 it will resolve it. But no, it is still there with following workspace 
- Debian 
- Thunderbird
- Discord
- Tor Browser.
![Screenshot_2024-06-22-16-12-49_17888](https://github.com/linuxserver/docker-firefox/assets/80718859/ca1ada3d-fcf0-411e-9e73-cb6275b5e7df)

**Comment by just-simon** [comment]
I've been receiving this error for over a month.

**Comment by thelamer** [comment]
This is fixed in latest. Also Firefox decided to implement the seamless clipboard in version 127 with an overlay button that needs to be clicked whenever you refocus the window because "muh privacy" so have fun with that.
