### ISSUE TITLE
[Question] Play DRM-controlled content

### ISSUE THREAD

**Issue by z6vcq** [linuxserver/docker-firefox#49]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Is it possible to play DRM-controlled content? 
In settings-general there is no DRM enabling setting 

### Reason for change

open.spotify.com doesn't work without DRM enabled
Best Regards

**Comment by thelamer** [comment]
This image is based on Alpine and widevine and other stuff is not available for MUSL. Unless this gets rebased to Debian DRM would not be possible.
