### ISSUE TITLE
[BUG] no title bar checkbox on Customise Toolbar

### ISSUE THREAD

**Issue by scorebook999** [linuxserver/docker-firefox#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

normally user can disable the title bar by uncheck the Title Bar checkbox from the Customise Toolbar,but i cant find this checkbox from this image

### Steps To Reproduce

Right-click the toolbar on firefox and select Customize Toolbar
Title Bar checkbox doesnt exist

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d --name=firefox \
  --cap-drop=ALL \
  --cap-add=CHOWN \
  --cap-add=SETGID \
  --cap-add=SETUID \
  --cap-add=DAC_OVERRIDE \
  --security-opt=no-new-privileges \
  --network=noicc \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e TITLE=Firefox \
  -e DOCKER_MODS=linuxserver/mods:firefox-fonts \
  -e DOCKER_MODS=linuxserver/mods:universal-package-install \
  -e INSTALL_PACKAGES=font-noto-cjk \
  -p 80:3000 \
  -p 443:3001 \
  -v /Firefox:/config \
  --tmpfs=/tmp:uid=1000,gid=1000,noexec,nosuid,nodev,noatime,mode=0700,size=4096m \
  --restart always \
lscr.io/linuxserver/firefox:latest
```

### Container logs

```bash
empty
```

**Comment by thelamer** [comment]
there is an env var for this: 
`-e NO_DECOR=true`

We just install firefox and lang packs from Alpine repos, the built in title bar management likely does not work in Alpine or Openbox or both.
