### ISSUE TITLE
Latest Tag is broken use 128.0.3

### ISSUE THREAD

**Issue by thelamer** [linuxserver/docker-firefox#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Firefox seems to only be able to access Google in Alpine in version 130. 

### Steps To Reproduce

Use latest tag

### CPU architecture

x86-64

### Docker creation

```bash
All systems
```

### Container logs

```bash
Logs are in browser
```

**Comment by hgabignon** [comment]
Thanks @thelamer , I was literally encountering the same issue and was about to file this as well.
It seems like Firefox is failing with SSL/TLS endpoints.

In the browser console, here is an extract of the messages:
```
HTTPS-First Mode: Upgrading insecure request “https://lemonde.fr/” failed. Downgrading to “http” again. lemonde.fr
```

(example for loading https://lemonde.fr)

**Comment by thelamer** [comment]
Just tested native Alpine and it works fine, this seems to be specific to our environment. Alpine is the choice because they have Firefox for aarch64 as well.
Ubuntu does not distro Firefox but does have a ppa and Debian outside of on unstable or using esr. The official Mozilla repos do not build aarch64 versions despite the nightly tag having them. So to support arm that leaves Arch and Fedora from our baseimage flavors.
Arch is a space hog when it comes to deps and Fedora is not used on almost anything but Webtop. 
I'll try out an Ubuntu rebase first just to have a plan B.

**Comment by thelamer** [comment]
The noble rebase can be tested using the tag `ghcr.io/linuxserver/lsiodev-firefox:latest`.
Anyone with existing data that can use this tag would be appreciated and will be a seamless transition to latest on the main repo if this is merged.

**Comment by qs-data** [comment]
> The noble rebase can be tested using the tag `ghcr.io/linuxserver/lsiodev-firefox:latest`. Anyone with existing data that can use this tag would be appreciated and will be a seamless transition to latest on the main repo if this is merged.

@thelamer I was worried I was going to have to try downgrade my user profile... the release with your tag worked for me

**Comment by thelamer** [comment]
The noble rebase has been merged, thanks for testing.
