### ISSUE TITLE
[FEAT] <title> add a way to install additionnal application (such as password manager)

### ISSUE THREAD

**Issue by castorfou** [linuxserver/docker-firefox#58]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I understand from docker-baseimage-kasmvnc there is a way to install in the image additional applications

in my case that would be enpass from https://apt.enpass.io/ 

and create an entry menu (with a menu.xml) as explained in https://github.com/linuxserver/docker-baseimage-kasmvnc?tab=readme-ov-file#in-container-application-launching

How could it be integrated in this repo logic? and to extend firefox with companion apps

### Reason for change

to provide a complete user experience

### Proposed code change

not sure how to do it

**Comment by thespad** [comment]
If you want a "complete user experience" then you should be using https://github.com/linuxserver/docker-webtop

The "named" images such as this one are designed for running single applications.
