### ISSUE TITLE
Can you provide SWAG subdomain.conf / subfolder.conf files so that this can be secured with Authelia

### ISSUE THREAD

**Issue by happening-primal** [linuxserver/docker-firefox#6]

**Comment by happening-primal** [comment]
Tried to figure this out on my own, but was unable...bit of a newb to nginx conf files.  Anyway, as the title suggests, it would be nice if there was a way to put this being Authelia 2FA.

**Comment by aptalca** [comment]
You can use the calibre one as it's the same rdesktop-web base. Just change all instances of calibre to Firefox and you should be good

**Comment by happening-primal** [comment]
Thanks for the supper quick reply.  

I made a copy of ~/docker/<my swag directory>/nginx/proxy-conf/calibre-web.subfolder.conf.sample as firefox.subfolder.conf in ~/docker/<my swag directory>/nginx/proxy-conf (contains all of the other proxy-conf files for swag) in of as per the below:

## Version 2021/05/18
# firefox does not require a base url setting

location /firefox {
    return 301 $scheme://$host/firefox/;
}

location ^~ /firefox/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /ldaplogin;

    # enable for Authelia, also enable authelia-server.conf in the default site config
    # To use Authelia to log in to Calibre-Web, make sure "Reverse Proxy Login" is 
    # enabled, "Reverse Proxy Header Name" is set to Remote-User, and each Authelia
    # user also has a corresponding user manually created in Calibre-Web.
    include /config/nginx/authelia-location.conf;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app firefox;
    set $upstream_port 3000;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Script-Name /firefox;
}

# OPDS feed for eBook reader apps
# Even if you use Authelia, the OPDS feed requires a password to be set for
# the user directly in Calibre-Web, as eBook reader apps don't support 
# form-based logins, only HTTP Basic auth.
#location ^~ /firefox/opds/ {
#    include /config/nginx/proxy.conf;
#    include /config/nginx/resolver.conf;
#    set $upstream_app firefox;
#    set $upstream_port 3000;
#    set $upstream_proto http;
#    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
#    proxy_set_header X-Scheme $scheme;
#    proxy_set_header X-Script-Name /firefox;
#}

My docker-compose.yml file contains the below and the container is running fine:

  firefox:
    image: lscr.io/linuxserver/firefox
    #container_name: firefox # Depricated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/<my path>/docker/firefox:/config
    ports:
      - 3000:3000
    shm_size: 1gb
    deploy:
      restart_policy:
       condition: on-failure

and I am getting this erro:

  Cannot GET /firefox/

when I navigate to https://<my_fqdn>/firefox/

Authelia requirs authentication before I get to the above url (https://<my_fqdn>/firefox/), and authelia is working for other services after authentication. 

Any help appreciated.

**Comment by aptalca** [comment]
`calibre` is not `calibre-web`

**Comment by happening-primal** [comment]
True... 
> `calibre` is not `calibre-web`

I was able to get this running, thanks for your help.  This is a really excellent addition and a quick way to get the results of remote browser isolation similar to paid services like webgap.io, authentic8's silo, or other self hosted solutions I tried like [browsergap](https://github.com/neuroradiology/browsergap.ce/blob/master/remote-browser-isolation.md) or [neko](https://github.com/m1k1o/neko) / [neko rooms](https://github.com/m1k1o/neko-rooms).  The only limitation I found was that the clipboard doesn't work between the host and the client.

For anyone wanting to run linuxserver.io firefox behind authelia, starting with the calibre.subfolder.conf file is easy and the changes are pretty simple.  All that needs to be done is to make a copy of calibre.subfolder.conf and name it firefox.subfolder.conf and then replace the word 'calibre' with the word 'firefox' in five places.  Be mindful of the line that reads:

     # In firefox docker arguments, set an env variable for SUBFOLDER=/firefox/

This needs to be added to your docker-compose.yml file as shown in the below example:

version: "3.1"

services:
&ensp;firefox:
&ensp;&ensp;image: lscr.io/linuxserver/firefox
&ensp;&ensp;#container_name: firefox # Depricated
&ensp;environment:
&ensp;&ensp;- PUID=1000
&ensp;&ensp;- PGID=1000
&ensp;&ensp;- TZ=Europe/London
&ensp;&ensp;- SUBFOLDER=/firefox/ # Required if using authelia to authenticate
&ensp;volumes:
&ensp;&ensp;- /home/my_user_directory/docker/firefox:/config
&ensp;ports:
&ensp;&ensp;- 3000:3000
&ensp;shm_size: 1gb
&ensp;deploy:
&ensp;&ensp;restart_policy:
&ensp;&ensp;&ensp;condition: on-failure

As I said, the altered calibre.subfolder.conf file should be named firefox.subfolder.conf and contain the following lines.  Note that you need to uncomment the line below for authelia to pick it up:

&emsp;&emsp;include /config/nginx/authelia-location.conf;

The contents of firefox.subfolder.conf should look like this:

\## Version 2021/06/28
\# In firefox docker arguments, set an env variable for SUBFOLDER=/firefox/

location /firefox {
&ensp;&ensp;return 301 $scheme://$host/firefox/;
}

location ^~ /firefox/ {
&ensp;&ensp;# enable the next two lines for http auth
&ensp;&ensp;#auth_basic "Restricted";
&ensp;&ensp;#auth_basic_user_file /config/nginx/.htpasswd;

&ensp;&ensp;# enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
&ensp;&ensp;#auth_request /auth;
&ensp;&ensp;#error_page 401 =200 /ldaplogin;

&ensp;&ensp;# enable for Authelia, also enable authelia-server.conf in the default site config
&ensp;&ensp;include /config/nginx/authelia-location.conf;

&ensp;&ensp;include /config/nginx/proxy.conf;
&ensp;&ensp;include /config/nginx/resolver.conf;
&ensp;&ensp;set $upstream_app firefox;
&ensp;&ensp;set $upstream_port 3000;
&ensp;&ensp;set $upstream_proto http;
&ensp;&ensp;proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
