### ISSUE TITLE
unable to play some videos asking for some codec

### ISSUE THREAD

**Issue by rahul1996pp** [linuxserver/docker-firefox#9]
Unable to play some videos it asking for install codecs

![image](https://user-images.githubusercontent.com/43852647/167704664-365953e1-5d5f-4609-b6ac-d3bc568a03d5.png)

**Comment by preslly** [comment]
I'm having the same issue, looks like we might need ffmpeg docker-mod for this docker image.

**Comment by m-theredhead** [comment]
You can use the container built in overrides to make this automatic.   

Under the config directory for firefox, create a file called custom-cont-init.d/install_ffmpeg

with the contents like:
#!/bin/bash
echo "**** installing ffmpeg ****"
apk add --no-cache ffmpeg

Then ffmpeg will get installed automatically after upgrades, etc.

**Comment by rahul1996pp** [comment]
Thank you

> sudo apk add --update ffmpeg

Thank you
